Added code for the reminder functionality
nihar4276/slackpoint-v2 pull request #26
Opened 2022-12-05 22:53 UTC by shrutiv123

Added code for the reminder functionality.

2022-12-05 23:01 UTC, sakshampandey27 requested changes

2022-12-05 23:01 UTC, sakshampandey27 commented on commands/reminders.py
> +        '''
Include function documentation, like for other functions

2022-12-05 23:01 UTC, sakshampandey27 commented on commands/reminders.py
> +            #print("task_text ",task_text)
Remove all print comments

2022-12-05 23:01 UTC, sakshampandey27 commented on commands/reminders.py
> +        '''
Fix documentation so that it resembles the standard followed throughout the code

2022-12-06 00:00 UTC, nihar4276 approved these changes

2022-12-06 00:23 UTC, sakshampandey27 approved these changes

2022-12-06 01:03 UTC, merged